-- MySQL Script generated by MySQL Workbench
-- Tue Oct  7 10:40:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema galaxy_impact_v
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema galaxy_impact_v
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `galaxy_impact_v` ;
USE `galaxy_impact_v` ;

-- -----------------------------------------------------
-- Table `galaxy_impact_v`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `galaxy_impact_v`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `galaxy_impact_v`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `pasword_hash` VARCHAR(100) NOT NULL,
  `fecha_registro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galaxy_impact_v`.`puntuaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `galaxy_impact_v`.`puntuaciones` ;

CREATE TABLE IF NOT EXISTS `galaxy_impact_v`.`puntuaciones` (
  `id_puntuacion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `puntuacion` INT NOT NULL,
  `nivel` INT NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`id_puntuacion`),
  INDEX `fk_puntuaciones_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_puntuaciones_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `galaxy_impact_v`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galaxy_impact_v`.`progreso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `galaxy_impact_v`.`progreso` ;

CREATE TABLE IF NOT EXISTS `galaxy_impact_v`.`progreso` (
  `id_progreso` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `nivel_actual` INT NOT NULL,
  `experiencia` INT NULL DEFAULT 0,
  `ultima_actualizacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_progreso`),
  INDEX `fk_progreso_usuario_idx` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_progreso_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `galaxy_impact_v`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galaxy_impact_v`.`logros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `galaxy_impact_v`.`logros` ;

CREATE TABLE IF NOT EXISTS `galaxy_impact_v`.`logros` (
  `id_logro` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL,
  `puntos_recompensa` INT NULL DEFAULT 0,
  PRIMARY KEY (`id_logro`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galaxy_impact_v`.`usuarios_logros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `galaxy_impact_v`.`usuarios_logros` ;

CREATE TABLE IF NOT EXISTS `galaxy_impact_v`.`usuarios_logros` (
  `id_usuario` INT NOT NULL,
  `id_logro` INT NOT NULL,
  `fecha_desbloqueo` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`, `id_logro`),
  INDEX `fk_ul_logro_idx` (`id_logro` ASC) VISIBLE,
  CONSTRAINT `fk_ul_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `galaxy_impact_v`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ul_logro`
    FOREIGN KEY (`id_logro`)
    REFERENCES `galaxy_impact_v`.`logros` (`id_logro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
